### ISSUE TITLE
infra: Set up archive node

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#186]
Give indexer access to oasis-2 (Cobalt) data by bringing up an oasis-2 node with all blocks, and including emerald.

@gw0 @amela do you have a config or even a node we can borrow from [operators-health](https://github.com/oasisprotocol/operators-health)? Looking at our charts, we're using the same v22 (= loose name for consensus v6 = oasis-3) node.

Impact until we have this:
- Consensus index will not have pre-Damask txs. However the account balances etc will be correct since the pre-Damask state is encoded in the Damask genesis file, which we do parse already.
- Emerald index will not have pre-Damask txs **and account balances will be wrong**. Paratime state is not encoded in the (consensus) genesis file. Setting up an archive node will not solve this automatically (there are [unresolved questions](https://github.com/oasisprotocol/oasis-indexer/issues/161) around migrating between versions), but it's a prerequisite, hence a highish priority.

**Subtasks:**
- [x] Design doc: dealing with node and paratime versions - https://github.com/oasisprotocol/oasis-indexer/issues/161
- [x] PoC: Convert oasis-core/oasis-sdk types to internal types
- [x] ops: Set up archive Cobalt node for consensus and Emerald - https://github.com/oasisprotocol/internal-ops/issues/508
- [x] db: Rename schema oasis_3 -> mainnet - https://github.com/oasisprotocol/nexus/pull/341
- [x] genesis indexing: UPDATE, don't just INSERT - https://github.com/oasisprotocol/nexus/issues/845
- [x] implement `RuntimeApiLite` (substitute for oasis-core, oasis-sdk) -https://github.com/oasisprotocol/nexus/issues/846
- [x] config: support multiple nodes - https://github.com/oasisprotocol/nexus/pull/352
- [x] implement remaining `ConsensusApiLite` methods for Cobalt - https://github.com/oasisprotocol/nexus/pull/356
- [x] refactor: do not use oasis-core types internally (except for node comms) - https://github.com/oasisprotocol/nexus/pull/356
- [x] config: support per-paratime nodes - https://github.com/oasisprotocol/nexus/pull/352

**Comment by gw0** [comment]
> Give indexer access to oasis-2 (Cobalt) data by bringing up an oasis-2 node with all blocks, and including emerald.

I guess you need gRPC access to a Mainnet v21.3 (Cobalt) archive node? Do you also need a Testnet v21.3 archive node?

> @gw0 @amela do you have a config or even a node we can borrow from [operators-health](https://github.com/oasisprotocol/operators-health)? Looking at our charts, we're using the same v22 (= loose name for consensus v6 = oasis-3) node.

Because it was a one-time import, we just spinned up a temporary archive node to run all the importers of `operators-health`. We deleted it afterwards.

**Comment by mitjat** [comment]
We'll eventually need both mainnet and testnet, first in staging and then in prod. However, we don't have the code yet to handle Cobalt (or rather, the migration from Cobalt to Damask), nor do we have the Emerald analyzer fully implemented, so this ticket is currently blocked.

Continuing in https://app.clickup.com/t/3ua4c4z

**Comment by csillag** [comment]
According to @pro-wh , this can be close now.
