### ISSUE TITLE
backfilling analyzer that parses EVM data once the ABI becomes available

### ISSUE THREAD

**Issue by csillag** [oasisprotocol/nexus#872]
**This is an old, completed issue, copying over for historical reference. No action is necessary.**

There are 3 pieces of data that are ABI-encoded:

*   evm.Log events
*   EVM txs (contents of the call)
*   EVM tx revert messages

We currently parse evm.Log events in the main runtime analyzer: we check if the event looks like an ERC20 Transfer, and if it does, we parse it. We do not parse txs in this sense at all (= parsing out fn names and args).

More broadly, we cannot do this for arbitrary events and txs unless we know the ABI of the contract.

Add a separate analyzer that checks if there are any contracts that 1) have a known ABI and 2) have associated events/txs that have not yet been parsed. If so, go ahead and parse those events/txs:

*   In the `runtime_events` table, we have evm\_\* fields that store the results of deep-parsing the event according to the emitting contract's ABI.
*   Add similar fields to the `runtime_transactions` table. An `evm.Call` can be parsed into a fn name and its args, etc. An evm.Create call ... probably does not use the ABI, but I'm not sure.
    *   Expose the new fields via our web API
*   For the revert reason, I think we can keep the old, simple format of a string, and the new field added in PR #530. So we'd store the JSON-serialized reason. Ugh ... but then a simple string should include the surrounding quotes. IDK. To be thought about.

Note: When the ABI is available when the log/tx is encountered, it would be nice to just process it synchronously, rather than in the new separate analyzer. But that would violate our three-phase analyzer design (fetch all data, analyze it, write to DB).

**Sub-tasks:**
- [x] use abi to parse ERC-20 events
- [x] utility lib for converting serialized_event + ABI ➝ JSON - #421 
- [x] backfilling analyzer for events - #540
